from django.db import models
  
# Create your models here.
class sq_model(models.Model):
    Latitude=models.FloatField(blank=True,null=True)
    Longitude=models.FloatField(blank=True,null=True)
    Unique_Squirrel_ID=models.TextField(blank=True,null=True)
    Shift=models.TextField(blank=True,null=True)
    Date=models.TextField(blank=True,null=True)
    Age=models.TextField(blank=True,null=True)
    Primary_Fur_Color=models.TextField(blank=True,null=True)
    Location=models.TextField(blank=True,null=True)
    Specific_Location=models.TextField(blank=True,null=True)
    Running=models.BooleanField(blank=True,null=True)
    Chasing = models.BooleanField(blank=True,null=True)
    Climbing = models.BooleanField(blank=True,null=True)
    Eating= models.BooleanField(blank=True,null=True)
    Foraging = models.BooleanField(blank=True,null=True)
    Other_Activities = models.CharField(max_length=200,blank=True,null=True)
    Kuks = models.BooleanField(blank=True,null=True)
    Quaas = models.BooleanField(blank=True,null=True)
    Moans = models.BooleanField(blank=True,null=True)
    Tail_flags = models.BooleanField(blank=True,null=True)
    Tail_twitches = models.BooleanField(blank=True,null=True)
    Approaches = models.BooleanField(blank=True,null=True)
    Indifferent = models.BooleanField(blank=True,null=True)
    Runs_from = models.BooleanField(blank=True,null=True)
