# Generated by Django 3.0 on 2019-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwsquirrel', '0003_auto_20191205_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq_model',
            name='Age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Chasing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Climbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Eating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Foraging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Indifferent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Kuks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Moans',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Primary_Fur_Color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Quaas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Runs_from',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Shift',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Specific_Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Tail_flags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Tail_twitches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sq_model',
            name='Unique_Squirrel_ID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
